### PR TITLE
add screenshot.png

### PR DESCRIPTION
**Pull request by slowkow**
I think visitors will appreciate a preview of the app without running code.

### CODE REVIEW

**Comment by federicomarini** [comment]
Good suggestion. 
I'd probably prefer to have the image hosted on something like google drive to keep the package as lightweight as possible? I'd let the others chime in too with their view on this

**Comment by slowkow** [comment]
Another option is to keep the image hosted on Github, and add these types of files to the `.Rbuildignore` so they don't end up in the package.

**Comment by kevinrue** [comment]
Screenshots were discussed during development of the package, and I think we all agreed that there is no real point spending significant package size into lots of screenshots.
With that said, I think we can probably invest a bit of package size into just one 'signature' screenshot of the app linked in both the `README` file and the vignette:
* the former would make it visible on GitHub
* the latter would make it visible in the vignette available from _Bioconductor_ package page.
In both cases, users would not have to install the package to see the screenshot.

**Comment by kevinrue** [comment]
PS: we could probably a mini-competition for the best screenshot :)

**Comment by LTLA** [comment]
I honestly don't see the need for a screenshot. I mean, people can just run it from the commands given in the vignette; it's really not a big deal, and you get the introductory tour, etc. I just don't see the added value of a screenshot. We'd also have to remember to update the static PNG every time we change the visuals of the interface; and it would bump up the package size (directly and via the vignette).

**Comment by kevinrue** [comment]
Particularly good point about having to update a screenshot (not to mention if there were multiple ones to maintain).
Just crossed my mind, having seen some GitHub websites recently: if people were _really_ desperate for a screenshot, we could set up a static website and host it up there: visible without impacting the package itself.
Shall we close this PR then?

**Comment by LTLA** [comment]
Yep, fine with me. Navigating to an external site would probably take more effort than just running the app locally, though. And if you aren't able to run the app locally, then having a screenshot would be like letting a starving man look through the window of a busy restaurant.

**Comment by slowkow** [comment]
This is an example of a good README: https://github.com/hms-dbmi/scde/blob/master/README.md

New visitors to the page want to *see* what the package does.

> people can just run it from the commands given in the vignette

Suppose you are a visitor who has never seen this page before. You want to get the gist of what this package is capable of, so you can decide if you should read further. Which option is better?

1. Look at a screenshot
  - less than 1 second, 0 commands, works on mobile devices, anyone can do it
2. Download R, install R, download and install packages, download and install data, etc.
  - Maybe 30 minutes to 1 hour for a beginner? What if they run into errors?
  - What about people who don't know how to run code?

> We'd also have to remember to update the static PNG every time we change the visuals of the interface

It's OK to have an out-of-date screenshot. The purpose of a screenshot is to immediately (with zero effort) answer the question "what does this package do?". Most people won't notice if the screenshot doesn't match the latest version of the code.

> and it would bump up the package size (directly and via the vignette).

Put `*.png` in `.Rbuildignore`. Alternatively, link from imgur or Google drive.

**Comment by slowkow** [comment]
@LTLA 

> like letting a starving man look through the window of a busy restaurant

image

**Comment by LTLA** [comment]
It's fine that some packages have screenshots. And it's fine that some don't. I don't particularly see the need for one here; installing an R package really isn't a big deal. And sure, users might not care if the screenshot is out of date - but I care, and that's another thing to worry about during maintenance. Especially given that the interface has the _iSEE_ version number stuck on it.

**Comment by federicomarini** [comment]
Probably this is going to be easier once some screenshots might also be in the vignette.
What would anyway be another possibility is the hex-logo, for which we are working on

**Comment by LTLA** [comment]
Or see https://cran.r-project.org/web/packages/webshot/vignettes/intro.html, for a fully automated solution from app instantiation. It does, however, require PhantomJS, so it would might not be practical to perform on the BioC build system. I could ask, or we could put it in the local build only.

**Comment by kevinrue** [comment]
Closing this issue, as it's essentially resolved by 48938d4fc6b25a99251fe6c310b440cecd324c0d

**Pull request closed without merging**
