### PR TITLE
Export .selectInputHidden

### PR DESCRIPTION
**Pull request by RiboRings**
Hi! This pull request aims to export .selectInputHidden so that it can be used in iSEEtree without importing it with `:::`. Please let me know if any other changes are needed before merging.

### CODE REVIEW

**Comment by kevinrue** [comment]
If it's exported, the man page can't be internal anymore. 

That might need a bit more thought than I anticipated..

**Comment by kevinrue** [comment]
Ow, i just noticed that you're working on your `devel` branch. It's not a problem right now, but once your PR is merged, you might find it a bit confusing as your `devel` branch won't be exactly the same as ours.
I'd say carry on for now, but once we merge your PR, you might be better off deleting your fork and forking again.

**Comment by RiboRings** [comment]
Oh ok! Thanks, I'll keep that in mind for next time. Also I realised that this issue is just throwing a note, not a warning, so it's not that urgent.

**Comment by kevinrue** [comment]
> Also I realised that this issue is just throwing a note, not a warning, so it's not that urgent.
Indeed.

also, at the moment, it doesn't seem possible to R CMD check the package due to the same issue affecting the Bioconductor Build System
https://bioconductor.org/checkResults/devel/bioc-LATEST/iSEE/nebbiolo2-buildsrc.html
```
failed to open file at '~/.cache/gypsum/bucket/scRNAseq/legacy/2023-12-18/allen/other_data/list_contents.json.gz'
```

**Comment by kevinrue** [comment]
Woohoo I found how to push to your devel branch!!

See https://github.com/iSEE/iSEE/actions/runs/10083191741/job/27879212702 for a successful run of github action of my own branch derived from yours.

You don't need to do anything. I'll merge when it passes. Once the next version is out, I'd appreciate if you could test iSEEtree without `:::`.

**Pull request merged**
