### PR TITLE
Sizeby

### PR DESCRIPTION
**Pull request by csoneson**
Allow sizing points by covariate

### CODE REVIEW

**Comment by kevinrue** [comment]
Worth a version bump?

**Comment by csoneson** [comment]
Done :)

**Comment by LTLA** [comment]
@csoneson should list herself as an author on the new sizing function.

**Comment by csoneson** [comment]
Ok, changed the authorship of the function. And there's one new line not covered by the unit tests...I'll add another test

**Comment by LTLA** [comment]
Why is the point size input removed? Is there any option for people to the the global point size under when size by is "none"?

**Comment by csoneson** [comment]
It's just moved - under "Visual parameters - Points", if Size by is "None", you can set the global point size.

**Comment by LTLA** [comment]
Good. Good.

**Pull request merged**
