### PR TITLE
Multiselections

### PR DESCRIPTION
**Pull request by LTLA**
Here be dragons.

# Urgent:

- [x] Pass `CHECK` -  many tests will now fail because of changes to existing functions to allow use of different selection other than the active selection in the transmitting plot.

# Refactoring

- [x] Make better use of reactive values to avoid repeating a lot of the logic in separate observers.

# Features:

- [x] Disable `Delete` button when there are no saved selections to delete.
- [x] Add option to supply **all** selections to custom functions, which was the whole point of this PR.

# Aesthetics:

- [x] Add a coloured number to each selection to indicate which one is 1, 2, 3, etc.
- [x] ~Remove shading from saved lasso selections, so that only the active selection is coloured.~

### CODE REVIEW

**Comment by LTLA** [comment]
c68d3e21bb78861997f0686905a761656bb10bb3 contains a truly bizarre fix.

The underlying bug is that, when the UI is rerendered (e.g., because the user changes the organization or sizing of the panels), the Shiny brushes are removed. This triggers the brush observers to remove the brushes from iSEE's internal memory. This is not desirable, as memorized brushes should persist.

Now, this behaviour is entirely expected when you think about it carefully, but somehow we had managed to avoid this in previous releases of _iSEE_. Why? Well, c68d3e21bb78861997f0686905a761656bb10bb3 contains the minimal hack required to get the expected behaviour on my machine (Ubuntu 16.04, Firefox 65.0, R-devel). I don't know why it works. 

In any case, this probably calls for some refactoring of how we handle brushes. I've noticed that sometimes the Shiny brushes are destroyed when Firefox resizes the window (e.g., due to opening/closing of the browser panel). It would be more robust to have an active signal for brush destruction, e.g., clicking.

**Comment by LTLA** [comment]
The handling of brushes is changed in 41ee187 to avoid relying on `NULL` brush inputs. Rather, Shiny (javascript) brushes are destroyed upon replotting, so the memorized brush is the "reference" that is used by all other observers. An explicit (double) click is required to destroy memorized brushes, which is reasonable.

**Comment by LTLA** [comment]
All free hands should confirm that brushing works on their computers with the latest `multiselect`. That is:

- Drawing a brush creates a rectangular box with a strong border. This box should persist even when the UI is rerendered, e.g., by reorganizing the panel layout or resizing individual panels.
- Clicking anywhere on the plot destroys an existing brush without creating a lasso waypoint.
- Double clicking destroys an existing brush and zooms in or out.

The current brush observer uses a hack to resolve between a standalone click and a click that is part of a brush (see the problem in rstudio/shiny#947). I don't know how stable the hack is, but without it, the brush box is drawn and then immediately disappears when the click observer is processed.

Currently, the hack works on:

- Firefox 65.0, Ubuntu 16.04 LTS, R-devel with _shiny_ 1.2.0
- Chrome 71, on the same computer.

You can freak it out by doing a lot of quick brushes or by doing very slow brushes, in which case the Javascript brush is not properly cleared... not sure whether this is the hack's fault or something else.

**Comment by federicomarini** [comment]
From my setup: works as expected.

Test machine: MacOS Sierra, Chrome 72.0.3626.109 + Firefox 65.0.1, with a `BiocManager::valid()` package ecosystem.

Safari (12.0.3) does not display some plots, but it has been behaving oddly in the last few days. So I think it is on my side.

> by doing very slow brushes, in which case the Javascript brush is not properly cleared... not sure whether this is the hack's fault or something else

I suspect this is unrelated to the hack. Sloooow lassos have been troublesome in previous versions.

**Comment by csoneson** [comment]
Works as expected for me too. 
MacOS High Sierra, Chrome 72.0.3626.109, R-devel, shiny 1.2.0. 
Also seems to work fine on Safari 12.0.3 on the same computer.

**Comment by federicomarini** [comment]
> Also seems to work fine on Safari 12.0.3 on the same computer.

Damn, that is because of my Safari then 😭

**Comment by kevinrue** [comment]
Alright, there are only 12 lines of codes in _total_ left uncovered in the package. We should be back to a coverage that Travis/Codecov will be happy to let us merge to `master`.
Also I've "fixed" redundant ggplot commands generated by a history including more than 1 lasso selection. I've tested interactively the definition of multiple lassos on the same plot and it all behaved well.

**Pull request merged**
