### PR TITLE
use "waszero"; do not touch "se" if not needed.

### PR DESCRIPTION
**Pull request by kevinrue**

### CODE REVIEW

**Comment by LTLA** [comment]
Good, and the same policy needs to apply for all `*Defaults()` functions.

**Comment by kevinrue** [comment]
Well.. note that a lot of the settings are delegated to functions like `.add_general_parameters_for_column_plots` which don't know (yet) what original `number` of panels was requested.
When it was 0, those functions are given the transient 1-row DataFrame.
To do what you describe, I can only imagine giving them an extra argument e.g. `zero=FALSE` to let me know that they only need to provide dummy values without checking the `se` to set the relevant columns in a 0-row DF?

**Comment by LTLA** [comment]
Perhaps it can just pick up `missing(se)`.

**Comment by LTLA** [comment]
Probably better to have `se=NULL` in such cases, which would allow you to simply do:

```r
extras <- add_general_parameters(incoming, se=if (waszero) NULL else se)
```

**Pull request merged**
