### PR TITLE
New allen

### PR DESCRIPTION
**Pull request by federicomarini**
Since the changes in `scRNAseq` on devel, `data(allen)` is now deprecated.
I changed all occurrencies I could find with `allen <- ReprocessedAllenData()`

### CODE REVIEW

**Comment by LTLA** [comment]
No need to coerce to an SCE, that's what it is natively now.

**Comment by federicomarini** [comment]
Shall we just go with `sce <-  ReprocessedAllenData()`?

**Comment by federicomarini** [comment]
I updated the calls and correspondingly also some text of the vignette where we referred to the `allen` object.
If it is ok for everyone, it is ready to merge - this would remove the warning status on the Bioc build machines.

**Comment by LTLA** [comment]
Do it.

**Comment by kevinrue** [comment]
I'm happy about merging this branch, though it still needs a version bump and an appropriate section in the NEWS file.
I'll try to do that now, but we're about to embark anytime, so feel free to do all that in the next 8h if you don't hear from me :)

**Comment by federicomarini** [comment]
Seems it is all ready to merge - and all green checks. I'm proceeding 😉

**Pull request merged**
