### PR TITLE
Preserve existing order of rows in *DataTable panels.

### LINKED ISSUE #657: Row/column data tables should ignore ordering of multiple selections
Currently, when `Row/ColumnDataTable` instances accept a multiple selection, they are subject to the ordering of rows/columns in the selection, e.g., 

https://github.com/iSEE/iSEE/blob/8f32b92fb8343bc77a16988cc3afc70d65b961fb/R/panel_ColumnDataTable.R#L140

We can see that `tab` is now ordered arbitrarily depending on what the upstream panel decided to pass along. I would wager that doing so is rather inappropriate, as the multiple selection doesn't have any concept of ordering. How the rows are ordered is the responsibility of the table, not of the upstream panels. A practical example for how this causes problems: the `RowDataTable` contains DE statistics and is already ordered meaningfully by p-value but receives a selection that changes that ordering.

So, a simple fix would be to switch to the same selection code used by the plots:

https://github.com/iSEE/iSEE/blob/8f32b92fb8343bc77a16988cc3afc70d65b961fb/R/family_ColumnDotPlot.R#L549

which gets rid of the ordering.

### PR DESCRIPTION
**Pull request by LTLA**
Closes #657.

### CODE REVIEW

**Comment by LTLA** [comment]
I don't know what the Mac failures are, but they don't seem related to my changes.

**Comment by kevinrue** [comment]
Dibs on 2.17.2 😜

https://github.com/iSEE/iSEE/pull/656

**Comment by kevinrue** [comment]
> I don't know what the Mac failures are, but they don't seem related to my changes.

Typical xml2-config issue when installing package XML. I'd ignore for now, at least until I can dig up the usual fix or it resolves itself.

**Comment by kevinrue** [comment]
Feel free to merge if ready. I've merged my PR and pushed upstream, so that it gets a chance to run on the BBS asap. I've version bumped this PR so that it triggers a new version when it's pushed upstream itself.

**Comment by LTLA** [comment]
I don't think I have BioC push permissions on this machine, so can you go ahead and do it?

**Comment by kevinrue** [comment]
Oh yeah of course I only meant your merge when you're ready. I'll push

**Pull request merged**
