### PR TITLE
Prerelease

### PR DESCRIPTION
**Pull request by LTLA**
Bunch of bugfixes.

### CODE REVIEW

**Comment by LTLA** [comment]
Is this fine? Can we merge?

**Comment by kevinrue** [comment]
No. Please check out #287 and merge that one first if you're happy with it. It's a side-side-branch where I experimented with the action button you suggested in #283 .

**Comment by kevinrue** [comment]
Note that #287 also contains a fix whereby the choices of the selectize input for reordering/adding/removing panels were the "long name" for the active ones, and the short identifier for the inactive/selectable ones.
See https://github.com/csoneson/iSEE/pull/287/files#diff-c2a9df1d3a982775cbea776dd07a81a8R506

**Comment by LTLA** [comment]
Check out the panel organization response and merge once done.

**Pull request merged**
