### PR TITLE
specified namespace for rowMeans function in the custom vignette

### PR DESCRIPTION
**Pull request by federicomarini**
A simple edit in the custom vignette.

In settings where the user might have also other packages loaded, it probably helps to disambiguate which function needs to be called.

@LTLA: I did change only in some spots where I thought it was necessary. Is it safe to replace it in all the occurrences?

### CODE REVIEW

**Comment by federicomarini** [comment]
Reason behind it: I almost went crazy while trying to set up a config with demo panels and other stuff open.
So if we could avoid the headaches to other potential customizers, I thought it does not hurt to specify that.

**Comment by federicomarini** [comment]
About the missing import.
Would a Suggests: Matrix be the correct way to specify this or do we need this package-wide?

**Comment by LTLA** [comment]
Welcome to the matrix generics hell:

https://stat.ethz.ch/pipermail/bioc-devel/2019-February/014641.html

**Comment by federicomarini** [comment]
Yep, I did follow a little the conversation on bioc-devel.

Are there any specific recommendation for the "dependency placement" in this case?

**Comment by LTLA** [comment]
No, there isn't. That's why it's such a pain to resolve.

**Comment by federicomarini** [comment]
Since we are approaching the release: is this something worth clarifying in the vignette, or should we leave it as it is?

**Comment by LTLA** [comment]
This is not really _iSEE_'s problem, but it doesn't hurt.

**Comment by federicomarini** [comment]
The only "problem" would be to have explicitly `Matrix` in the dependencies, to be precise in the `Suggests:`. 

AFAIK we do already leverage that package via namespaces, so it would not add extra burden. At least, to the best of my knowledge

**Comment by LTLA** [comment]
/shrug. Go ahead.

**Comment by LTLA** [comment]
Happily, this entire issue will be fixed once [this](https://stat.ethz.ch/pipermail/bioc-devel/2019-April/014894.html) gets into R-devel.

**Comment by LTLA** [comment]
This should no longer be necessary, `rowMeans` is now the same generic in _BiocGenerics_ and base.

**Pull request closed without merging**
